services:
    satori.api.serializer.serializer:
        class: Satori\Api\Lib\Serializer\Serializer
        arguments: ["@jms_serializer", "@doctrine.orm.entity_manager"]

    satori.api.entity_context:
        class: Satori\Api\Lib\EntityContext
        shared: false

    satori.api.configurator.virtual_field:
        class: Satori\Api\Lib\Configurator\VirtualField
        shared: false

    satori.api.configurator.entity_configurator:
        shared: false
        class: Satori\Api\Lib\Configurator\EntityConfigurator
        arguments: ["@doctrine.orm.entity_manager", "@validator", "@satori.api.entity_context", "@satori.api.configurator.virtual_field"]

    satori.api.abstract_api_controller:
        class: Satori\Api\Lib\AbstractApiController
        abstract: true
        arguments: ["@request_stack"]
        calls:
          - [setContainer, ['@service_container']]
